### ISSUE TITLE
New maintainer?

### ISSUE THREAD

**Issue by rfk** [pyenchant/pyenchant#129]
I've temporarily un-archived this repo, because I realized that closing down issue discussions might prevent potential new maintainers from coordinating with each other.  If you're interested in keeping this project kicking, please weigh in here, and I'm happy to help coordinate a handoff to someone with the bandwidth to maintain it going forward.

**Comment by GadgetSteve** [comment]
I'll consider stepping in - it will be the first taste of maintaining a live project for me so I may need a little hand holding at first. I don't have a Mac available any local Mac build & testing will have to be in a VM or via an online build service.

**Comment by rfk** [comment]
Hi @GadgetSteve, thanks for reaching out!  Let's chat about what might be involved and see what you think :-)

> I don't have a Mac available any local Mac build & testing will have to be in a VM
> or via an online build service.

One of the main issues with this project currently is the rather clunky build process, which makes it time-consuming to cut releases and has prevented e.g. win64 support.  A good place to start might be to try building the underlying enchant library on the platforms you have available and see what that process looks like:

  https://github.com/AbiWord/enchant

I haven't tried building it since development started on the version 2 series of enchant, so it's possible that things have gotten a build easier since then.

**Comment by kevswanberg** [comment]
I'm interested @rfk anything you want to go over with the build process for releasing? I think making sure that the install works with version 2 of enchant lib installed is important.

I've built current version of enchant on Linux and am working on windows as well

**Comment by rfk** [comment]
Hi @kevswanberg, thanks for reaching out and sorry for the delay replying here.  For the build process, take a look at the resources under:

  https://github.com/rfk/pyenchant/tree/master/tools/pyenchant-bdist-osx-sources
  https://github.com/rfk/pyenchant/tree/master/tools/pyenchant-bdist-win32-sources

To get a sense of what's involved on different platforms.  The OSX one I think is pretty straightforward thanks to homebrew; the windows one depends on a bunch of pre-compiled dlls which we'd ideally move away from using.  Did you have any luck with your exploration of building on windows?

**Comment by mcallaghan-bsm** [comment]
For those who've expressed interest so far, any updates to share?

We are considering to include/leverage pyenchant, however active maintenance is an important aspect in the decision making.

**Comment by dmerejkowsky** [comment]
Hi there,

I'm volunteering for taking up maintainance of this cool project. Let me know how to move forward. 

I've some experience with CI so I'd be glad to help

**Comment by rfk** [comment]
Hi @dmerejkowsky, thanks for your interest!

As noted in https://github.com/rfk/pyenchant/issues/129#issuecomment-433833919 above, the tricky part here has been building the [underlying enchant library](https://github.com/AbiWord/enchant) in a reliable manner for different platforms, particularly on Windows. Do you have access to a Windows machine or CI environment?  A great way to start would be to try building the enchant dependency for Windows (perhaps by following my [somewhat outdated build scripts](https://github.com/rfk/pyenchant/tree/master/tools/pyenchant-bdist-win32-sources)).

If you're able to make a build of `libenchant.dll`, put it somewhere where [pyenchant's loading logic](https://github.com/rfk/pyenchant/blob/master/enchant/_enchant.py#L84) can find it, and successfully `import enchant` on a Windows platform, then I reckon you will have overcome the biggest roadblock to ongoing maintenance of this project.

**Comment by dmerejkowsky** [comment]
> building the underlying enchant library in a reliable manner for different platforms, particularly on 
Windows.

Yeay, building C++ on Windows can be challenging at time. But I've dealt with these kinds of issues several times :)

> Do you have access to a Windows machine or CI environment? 

I do. Do you mind if we use GitHub actions for this? We can stay with travis if you prefer.

>  I reckon you will have overcome the biggest roadblock to ongoing maintenance of this project.

Perfect. Let's do this!

**Comment by rfk** [comment]
> Do you mind if we use GitHub actions for this?

I'm pretty open-minded, let's give it a shot :-)

I'll add you as a collaborator on this repo, but let me know what else you might need in order to get github actions up and running.

**Comment by dmerejkowsky** [comment]
> I'll add you as a collaborator on this repo

Thanks :) I've started merging a few basic PRs and commenting on "easy" open issues.

I'm wondering about Python2 support: do you think we can drop it? Python3 EOL is 2 months

**Comment by dmerejkowsky** [comment]
So here's my short-term goals:

* [ ] Drop Python2 support unless there's a really good reason
* [ ] Rework CI, especially on Windows. The goal is to have binaries wheels for all supported operating systems and Python versions. We'll do it using GitHub Actions
* [ ] Make a new release containing long-awaited fixes like not using deprecated `wx `API (#132) or supporting latest enchant library name (#130)

**Comment by dmerejkowsky** [comment]
Update: I've created two milestones so that you can all see what I'm planning to do.

"Next release" is for urgent and important issues, "cleanups" is for lower priority tasks.

**Comment by dmerejkowsky** [comment]
@rfk I will need access on pypi.org to upload the next release. Can you please add me as a maintainer on pypi.org ? My login there is `Dimitri.Merejkowsky`

**Comment by rfk** [comment]
> Can you please add me as a maintainer on pypi.org ? My login there is Dimitri.Merejkowsky

Done, sorry for the delay.

> You can either grant me admin access on this repo, or I can create a pyenchant organisation and redirect this repo there. 

Moving this repo to an organization sounds good to me, if that works for you 👍

**Comment by dmerejkowsky** [comment]
> Done, sorry for the delay.

No problem, there's still lots to do before the next release

> Moving this repo to an organization sounds good to me

Also done. Thanks

**Comment by dmerejkowsky** [comment]
It has been done. Let's close our 100th issue ;)
