### ISSUE TITLE
Accessing full en_US word list

### ISSUE THREAD

**Issue by jadeshi** [pyenchant/pyenchant#138]
I was wondering if it was possible to access the full list of words that the Dict object compares against when spellchecking? Thanks for the help
!

**Comment by dmerejkowsky** [comment]
I don't think so. I'm curious about *why* you would need that information, though.

Also, it's possible you get better answers directly from the upstream enchant project: https://github.com/Abiword/enchant

**Comment by jenstroeger** [comment]
@jadeshi, perhaps this helps:
```python
>>> d = enchant.Dict('en_US')
>>> d.suggest('foo')
['few', 'foot', 'fool', 'food', 'too', 'coo', 'goo', 'moo', 'boo', 'woo', 'zoo', 'Koo', 'fro', 'foe', 'for']
```

**Comment by PanderMusubi** [comment]
This is not possible. The underlying spell checking libraries used to have tools to reverse engineer a word list from the dictionary (which is in a completely different format than a flat word list), but these tools no longer work as the complexity of the dictionaries have increased.

If you are looking for words lists (often provided by the makers of the spell checking dictionaries) please see https://github.com/nuspell/nuspell/wiki/Ubuntu-word-list-packages for an overview. For `en_US` there are different versions (in size) available.

I think this issue can be closed.

**Comment by PanderMusubi** [comment]
Upstream is [SCOWL]9http://wordlist.aspell.net/)

**Comment by dmerejkowsky** [comment]
Thanks for the detailed respose, @PanderMusubi  :)

Closing
