### ISSUE TITLE
Proper windows support

### ISSUE THREAD

**Issue by dmerejkowsky** [pyenchant/pyenchant#140]
We need to build the dll on Windows, and put it inside the wheel.

Starting points:
* Build scripts for win32: https://github.com/rfk/pyenchant/tree/master/tools/pyenchant-bdist-win32-sources
* Appveyor stuff in upstream library: https://github.com/AbiWord/enchant/blob/master/appveyor.yml

When this is done maybe we can move on with fixing #92 (adding windows 64 bits)

**Comment by rfk** [comment]
Just to note that `pyenchant-bdist-win32-sources` contains a couple of patches against upstream enchant library. They may or may not still be necessary now that development on the upstream library seems to be reinvigorated, it's probably worth trying it without them and seeing if any tests break.

**Comment by dmerejkowsky** [comment]
I'll keep that in mind. Thanks for the info

**Comment by dmerejkowsky** [comment]
Blocked by https://github.com/AbiWord/enchant/issues/226 :/

**Comment by dmerejkowsky** [comment]
An other possibility is to use a Windows specific provider using built-in SpellCheck.h on windows:
https://docs.microsoft.com/en-us/windows/win32/api/spellcheck/
https://github.com/hexchat/hexchat/blob/master/src/libenchant_win8/win8_provider.cpp

**Comment by dmerejkowsky** [comment]
A 3rd possibility is to use: https://pypi.org/project/pyspellchecker/ by wrapping a facade for PyEnchant.

**Comment by dmerejkowsky** [comment]
OK, new strategy :)

I've forked the upstream enchant project into this organization and configured AppVeyor so that we get all the artifacts we need for pyenchant.

And it almost works!

In the pyenchant/enchant `appveyor-artifacts` branch we build Hunspell and Enchant from scratch, then put them in an artifact

In the `windows` branch of this repo we read the PYENCHANT_ENCHANT_PREFIX to:
* load the enchant dll
* call `enchant_set_prefix_dir` so that enchant plugins are found
 
And then:

```python
>>> import enchant
>>> broker = enchant.Broker()
>>> broker.describe()
[<Enchant: Hunspell Provider>]
>>> broker.list_dicts()
[]
```

All that's left to do is to document how to download hunspell dicts and where to put them so that the enchant plugin finds them.

Then we can re-add the logic to read the enchant prefix using pkg_resources and write the CI code to properly generate the wheel.

Almost there :)

**Comment by dmerejkowsky** [comment]
_Update_: managed to get almost all tests passing! (see #174)

You can just grab dictionnaries from the mingw package and place them under `<enchant_prefix>/share/enchant/hunspell`

**Comment by dmerejkowsky** [comment]
_Update_: Well we still have two failures to fix. One on pypy3 and one on python3.8

See the `windows` branch for details
