### ISSUE TITLE
Move to pyenchant organisation

### ISSUE THREAD

**Issue by dmerejkowsky** [pyenchant/pyenchant#157]
By "moving the repo", I mean using the `transfer ownership` button in the Danger Zone of the admin settings, _not_ creating a fork.

Poke @rfk - I'm not admin on this repo so I can't do it myself.

Doing so will allow us to:

* Use gh-pages to host the website - the current one is dead and I can't configure gh-pages on this repo
* Allow more (or different) maintainers in the future :)

If this takes too long, we can always fork this repo in the `pyenchant` organization but then we'd lost all the stars, forks and issues of this project :/

**Comment by rfk** [comment]
Done 👍
