### ISSUE TITLE
d.check('cpu') return False ?Why?

### ISSUE THREAD

**Issue by DasyDong** [pyenchant/pyenchant#163]
I am new met pyenchant, I don't know why some words been spelled False? 
eg:
 github
 cpu
 kubernetes
```
import enchant
d = enchant.Dict("en_EN")
d.check('github')
False
d.check('cpu')
False
d.check('kubernetes')
False
```

print(vars(d.provider))  , my output : 
{'name': 'myspell', 'file': '/Library/Python/2.7/site-packages/enchant/lib/enchant/libenchant_myspell.so', 'desc': 'Myspell Provider'}

what the correct way to use enchant? i am  wrong? 

Thanks Everybody

**Comment by dmerejkowsky** [comment]
Well, `cpu`, `github` and `kubernetes` are not English words per se and myspell does not know about them.

You can add them in your personal word list if you wish.

Side note: myspell is case sensitive, so you may want to add `CPU`, `GitHub`, and `Kubernetes`

**Comment by DasyDong** [comment]
thanks a lot !   Thank you for your note too
