### ISSUE TITLE
Load dictionary files manually.

### ISSUE THREAD

**Issue by jenstroeger** [pyenchant/pyenchant#167]
At the moment it looks to me as if PyEnchant relies on the provider (via the [`enchant` library](https://github.com/AbiWord/enchant)<sup>*</sup>) to supply the speller & dictionary files, e.g. [`hunspell`](https://hunspell.github.io/) or [`GNU ispell`](https://www.gnu.org/software/ispell/) (which seems to have been replaced by [`aspell`](http://aspell.net/)).

Alas, I don’t always have permission to install dictionaries for these packages on the host system and, furthermore, I’d like to ship dictionaries as part of the Python package itself.

I found a somewhat hacky solution to achieving this [here](https://stackoverflow.com/questions/10922546/pyenchant-cant-find-dictionary-file-on-mac-os-x#12170877):
```python
>>> enchant.set_param("enchant.myspell.dictionary.path","/Library/Python/2.7/site-packages/pyenchant-1.6.5-py2.7.egg/enchant/share/enchant/myspell")  
>>> d=enchant.Dict("en_US")
>>> d.check("enchant")  
True  
```
and I was wondering if that is the recommended way, or if perhaps this can be simplified by adding constructor parameters or a new method to a [Broker](https://github.com/pyenchant/pyenchant/blob/8a62a2562ff02546f45ff27d11259f5fee6853a7/enchant/__init__.py#L197)?

Suppose, for example, I run Python as a guest on a random Linux machine where:
```python
>>> import enchant
>>> enchant._broker.describe()
[<Enchant: Aspell Provider>, <Enchant: Myspell Provider>]
```
and the language I need is not amongst the `enchant._broker.list_languages()`:
```python
>>> 'pt_BR' in enchant._broker.list_languages()
True
>>> 'pi_PI' in enchant._broker.list_languages()
False
```
Then I’d like to be able to ship the required dictionary files as part of my package, and feed the dictionary from the Python package to enchant. Another useful scenario is that I’d like to override a locally installed `en_US` with a more complete dictionary from [SCOWL](http://wordlist.aspell.net/dicts/).

—————
<sup>*</sup> Disclaimer: I’m currently unfamiliar with the `enchant` library itself…

**Comment by dmerejkowsky** [comment]
> I found a somewhat hacky solution to achieving this here:

I won't call it hacky, but it's using the `broker_set_param` method that was unfortunately removed from the C library in the 2.0.0 release: https://github.com/AbiWord/enchant/blob/master/NEWS#L103

> I was wondering if that is the recommended way, or if perhaps this can be simplified by adding constructor parameters or a new method to a Broker?

I don't know. We should investigate this further

**Comment by jenstroeger** [comment]
Might not help with the enchant library, but this is from aspell:
```
> aspell --help

...

Available Dictionaries:
    Dictionaries can be selected directly via the "-d" or "master"
    option.  They can also be selected indirectly via the "lang",
    "variety", and "size" options.


  af
  be
  be_BY
  be_SU
  bg
...
```
So, while enchant may make selecting a dictionary a bit tricky, it seems that aspell can select from an installed one. How to select a dictionary from an _arbitrary_ path though… 🤔

**Comment by PanderMusubi** [comment]
Enchant an list all languages supported. Note that the history of spell checker development is ispell, aspell and hunspell, in that order. It sort of that they replace one after the other, but that is not important here, Enchant is there to not worry about that and simply get a (the _best_) spell checker for a specific language.

See also:

    enchant-lsmod-2
    enchant-lsmod-2 -list-dicts

**Comment by dmerejkowsky** [comment]
I don't think it blocks the next release - my priority is to make a new release with same feature scope, we can worry about additional features letter.

@jenstroeger let me know if you disagree :)

**Comment by PanderMusubi** [comment]
Just to inform you, a new release of Enchant is upcoming, probably somewhere this week.

**Comment by dmerejkowsky** [comment]
Thanks for letting me know :)

**Comment by jenstroeger** [comment]
> I don't think it blocks the next release - my priority is to make a new release with the same feature scope, we can worry about additional features letter.

@dmerejkowsky, that’s ok with me 👍

**Comment by Jenyay** [comment]
Thank you for evolution of pyenchant. I use the method broker.set_param('enchant.myspell.dictionary.path', path) to load dictionaries, but in pyenchant 3.0.0.rc3 this the call leads to an error:

``` python
File "C:\Users\Room622-2\.virtualenvs\outwiker-Lf6h2J52\lib\site-packages\enchant\__init__.py", line 477, in set_param
    _e.broker_set_param(self._this, name, value)
TypeError: broker_set_param() takes 2 positional arguments but 3 were given
```

broker_set_param accepts only two parameters:

``` python
try:
    broker_set_param = e.enchant_broker_set_param
except AttributeError:
    #  Make the lookup error occur at runtime
    def broker_set_param(broker, param_name):
        return e.enchant_broker_set_param(param_name)
```

**Comment by dmerejkowsky** [comment]
Thank you for the beta-testing :)

Note that the PyEnchant wheel contains a pre-compiled Enchant C library at version 2.2.7, 
so calling `broker.set_param()` is doomed to fail.

That being said, it should have failed with `AttributeError` instead of `TypeError`. I've opened #187 since this is a separate issue.

**Comment by Jenyay** [comment]
Hunspell can read dictionaries from the folders listed in the DICPATH environment variable. Maybe it works for enchant.

**Comment by rrthomas** [comment]
Hi, Enchant maintainer here. Support is already built in! Unfortunately it's back-end dependent: it only works for hunspell and nuspell.

In both cases, dictionaries can be stored under `USER_CONFIG_DIR/PROVIDER_NAME/`, for example `~/.config/enchant/hunspell`. By `USER_CONFIG_DIR` I mean the return value of `enchant_get_user_config_dir()`, which defaults to the environment variable `ENCHANT_CONFIG_DIR`.

I've filed an issue https://github.com/AbiWord/enchant/issues/239 about documenting this.

**Comment by dmerejkowsky** [comment]
Let's close this, then
