### ISSUE TITLE
Contact downstream maintainers

### ISSUE THREAD

**Issue by dmerejkowsky** [pyenchant/pyenchant#172]
Debian for instance needs to know that the URL has changed

**Comment by hosiet** [comment]
https://tracker.debian.org/pkg/pyenchant

Looking at the maintainer field, maybe you could send a email to piotr (At) debian.org. Anyway currently Debian's pyenchant package has already been monitoring your repo as the upstream (see the homepage field at https://tracker.debian.org/pkg/pyenchant). This change will be reflected in Ubuntu 20.04 LTS (but not earlier versions).

**Comment by dmerejkowsky** [comment]
Thank your for the information, @hosiet

**Comment by dmerejkowsky** [comment]
Mail sent, let's close this
