### ISSUE TITLE
First 3.0 release candidate is out

### ISSUE THREAD

**Issue by dmerejkowsky** [pyenchant/pyenchant#182]
You can try by runnig somethnig like:

```
pip install pyenchant==3.0.0rc2
```

This is the first in the 3.0 series to have full support for Windows.

Make sure you get a recent enough pip so that you download the appropriate wheel from https://pypi.org/project/pyenchant/3.0.0rc2/#files

If you get an error about the enchant library not found, please [read the documentation](https://pyenchant.github.io/pyenchant/install.html) and if required, open a bug report - don't forget to set `PYENCHANT_VERBOSE_FIND`.

Cheers!

**Comment by dmerejkowsky** [comment]
I've just released 3.0.0rc3. The Windows wheels are now much lighter (12MB intstead of 22MB) , they used to contain a bunch of unneeded dlls...

**Comment by bgermann** [comment]
Thanks for picking up pyenchant! Would you please add the licenses of all the binaries in the wheel? Most of them should require adding the license for legal distribution.

**Comment by dmerejkowsky** [comment]
Good point. Thanks for letting me know

**Comment by bgermann** [comment]
I would also suggest to not have a blacklist in this repo for the enchant-prefix* binaries from https://github.com/pyenchant/enchant/releases but to only distribute the libraries you need there.

**Comment by dmerejkowsky** [comment]
Yup. I took a few shortcuts by keeping all the dlls from the appveyor build just in case.
Now that I know exactly what to include :)

**Comment by dmerejkowsky** [comment]
Let's close this now that 3.0.0 is officially out!
