### ISSUE TITLE
Fix PyPI Homepage URL

### ISSUE THREAD

**Issue by PanderMusubi** [pyenchant/pyenchant#186]
Please, fix the PyPI Homepage URL that points to https://pythonhosted.org/pyenchant/ Also check where this old URL needs to be replaced as well.

**Comment by dmerejkowsky** [comment]
This will be done automatically once the 3.0.0 stable release is out.
There's just one bug left: #184 - feel free to help us get there, and thank you for your understanding.

**Comment by PanderMusubi** [comment]
Thanks. Sorry, no experience with wheels.
