### ISSUE TITLE
Consider adding an optional language tag to personal wordlist?

### ISSUE THREAD

**Issue by jenstroeger** [pyenchant/pyenchant#193]
I realize that a personal word list can contain any assortment of words, which don’t even have to belong to the same language. And so…
```
>>> import enchant
>>> pwl = enchant.request_pwl_dict('en_US.pwl')  # , tag="en_US")
>>> pwl.tag
'Personal Wordlist'
```
I wonder if adding an optional parameter, defaulting to `None`, would be useful here where I can pass in a language tag for a pwl.

Personally, I’d find that useful for debugging purposes because I work with different pwls which actually do contain language specific words.

**Comment by dmerejkowsky** [comment]
I think the correct way to implement this would be to add the feature in  the Enchant C library it self, not in PyEnchant itself (which is only a wrapper on top of the C library) - I suggest you open an issue on Enchant's bug tracker
