### ISSUE TITLE
For a single letter followed by two periods, it can pass the check.

### ISSUE THREAD

**Issue by liuyuanOUC** [pyenchant/pyenchant#194]
Hello, the enchant works well. But I found an error.
A single letter followed by two periods is considered a valid word by the enchant. The enchant version is 3.0.1.

**Environment**
Python version: Python 3.7.4 for Windows; Python 3.6.9 for Ubuntu
Operation system: Windows 10 1909 and Ubuntu 18.04.3 LTS

```python
>>> import enchant
>>> d = enchant.Dict("en_US")
>>> d.check("b..")  # return True
>>> d.check("B..")  # return True
```

**Comment by dmerejkowsky** [comment]
Sorry, I could not reproduce the bug. Can you please put the output of ` vars(d)`  ?

**Comment by liuyuanOUC** [comment]
windows
![figure1](https://user-images.githubusercontent.com/27879832/79173675-e86d7580-7dbd-11ea-88ca-1487d02e1ccb.png)
Linux
![figure2](https://user-images.githubusercontent.com/27879832/79173689-f0c5b080-7dbd-11ea-8f4b-6c136e997535.png)

@dmerejkowsky Hi, thanks for your prompt reply. you can see the `vars(d)` from the above figures.

**Comment by dmerejkowsky** [comment]
Interesting - it looks like the bug does not happen with aspell, but does happen with hunspell or myspell

**Comment by dmerejkowsky** [comment]
I just confirmed : this is a bug in `hunspell`, not PyEnchant or even Enchant:

```bash
$ echo "hello worldd b.. missstake" | hunspell -l
worldd
missstake
```

I suggest you go open a bug on hunspell bug tracker.
