### ISSUE TITLE
pyenchant 3.0.1 python 3.8.2 ubuntu 20.04 libffi.so.6 does not exist

### ISSUE THREAD

**Issue by elguavas** [pyenchant/pyenchant#195]
hi there, using pyenchant in the environment specified in the title gives the following traceback:

>>> import enchant
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/smg/.pyenv/versions/3.8.2_quill/lib/python3.8/site-packages/enchant/__init__.py", line 81, in <module>
    from enchant import _enchant as _e
  File "/home/smg/.pyenv/versions/3.8.2_quill/lib/python3.8/site-packages/enchant/_enchant.py", line 55, in <module>
    import ctypes
  File "/home/smg/.pyenv/versions/3.8.2/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory

libffi6 does not exist and is not installable on this version of linux, libffi7 is installed by deafult.
so libffi.so.7 exists but not libffi.so.6 .
can pyenchant be updated to support the modern libffi ?

thanks.

**Comment by dmerejkowsky** [comment]
So I've tried to reproduce the bug in a docker image with Python 3.8 installed both from the official repositories and pyvenv but with no avail.

I think the issue comes from the way you've built Python, but I don't get is the weird `_quill` suffix in your pyenv installation path - can you give details ?

**Comment by elguavas** [comment]
> So I've tried to reproduce the bug in a docker image with Python 3.8 installed both from the official repositories and pyvenv but with no avail.
> 
> I think the issue comes from the way you've built Python, but I don't get is the weird `_quill` suffix in your pyenv installation path - can you give details ?

yeah, nope nothing to do with the python build. to answer your questions, the _quill suffix is purely because its a pyenv virtualenv (based on the pyenv 8.2 build) for a particular project. my pyenv 8.2 build is a regular pyenv 8.2 build, nothing unusual there.

the actual final error relates to pyenchant 3.0.1 (from pypi) needing a particular version of libffi, a verison of libffi which is no longer available on *buntu 20.04. 

if you tried this on an actual *buntu 20.04 install you would get the same problem. (i've tried it on both my main pc and my laptop, and on the laptop it was with the system python, not a pyenv build).

libffi.so.6, which the pypi install of pyenchant 3.0.1 is specifically looking for, simply does not exist on *buntu 20.04, it has libffi.so.7 .

if i create a symlink from libffi.so.7 as the name libffi.so.6, everything actually works fine, which proves it's simply the libffi version problem, not anything else.

the point of this problem report is that *buntu 20.04 is the latest *buntu version (in rc right now) and i don't think people who run the current pyenchant from pypi on the latest ubuntu should have to manually create a symlink to get it to work.

**Comment by elguavas** [comment]
...sorry i accidentally closed this, reopenned now.

**Comment by elguavas** [comment]
ok, i've solved this. :)

it was your remark that you thought it was a python build issue that led me to the solution. i decided to look into that more closely. 

first i realised that my laptop install of the project was actually now using a pyenv virtualenv created the same way (i changed my laptop copy of the project to be set up the same as my pc copy just recently) and that the laptop has also just been _upgraded_ from kubuntu 19.10 to 20.04, just as my pc has.

then i realised that the pyenv installs of python 3.8.2 had been created under the previous kubuntu version. *sigh*

so i rebuilt the pyenv 3.8.2 on kubuntu 20.04 (so the pyenv build now pulled in kubunu 20.04 libraries) and recreated my pyenv virtualenv.

problem solved. ;)

so thanks for setting me on the right track  Dimitri, and thanks for your time.

(and sorry for the static in the pyenchant github issues. ;) )

you can close this now, i only left it open so you would see how i fixed it by correcting my own oversight.

**Comment by dmerejkowsky** [comment]
Cool, glad I could help.

> if i create a symlink from libffi.so.7 as the name libffi.so.6, everything actually works fine, which proves it's simply the libffi version problem, not anything else.

Also, could not resist : I see this advice "just create the symlink with the correct name"  pop up quit often - it's almost *always* a very bad idea which could cause problems much worse than the one you are trying to solve.

**Comment by dmerejkowsky** [comment]
And thus, I made a long blog post to explain why : https://dmerej.info/blog/post/symlinks-and-so-files-on-linux/

**Comment by M-AamirBakhtiar** [comment]
> ok, i've solved this. :)
> 
> it was your remark that you thought it was a python build issue that led me to the solution. i decided to look into that more closely.
> 
> first i realised that my laptop install of the project was actually now using a pyenv virtualenv created the same way (i changed my laptop copy of the project to be set up the same as my pc copy just recently) and that the laptop has also just been _upgraded_ from kubuntu 19.10 to 20.04, just as my pc has.
> 
> then i realised that the pyenv installs of python 3.8.2 had been created under the previous kubuntu version. _sigh_
> 
> so i rebuilt the pyenv 3.8.2 on kubuntu 20.04 (so the pyenv build now pulled in kubunu 20.04 libraries) and recreated my pyenv virtualenv.
> 
> problem solved. ;)
> 
> so thanks for setting me on the right track Dimitri, and thanks for your time.
> 
> (and sorry for the static in the pyenchant github issues. ;) )
> 
> you can close this now, i only left it open so you would see how i fixed it by correcting my own oversight.

I am new to Ubuntu and while trying to install  autopep8  by doing pipenv install autopep8 --dev i get the same error  of libffi.so.6.  How can i do a rebuild like you so solve this? (while googling i have seen other people also doing a rebuild of python and that would fix the issue but they never mentioned how the rebuild was done)
