### ISSUE TITLE
No languages included? 

### ISSUE THREAD

**Issue by bgenchel** [pyenchant/pyenchant#199]
Thank you for taking the time to open a bug report!

If you haven't already, take a time to look at the [documentation](https://pyenchant.github.io/pyenchant/). Maybe the answer to your problem can be found there?

If not, please fill in the details below to help us help you 🙂

**Environment**
Python version: 3.8.0
Operation system: Amazon Linux

**Additional context**

**Steps to Reproduce**
Please specify steps to reproduce the incorrect behavior:
install pyenchant, import enchant, try to make a dictionary object for any language code or try `enchant.list_languages()` to find that the list is empty

**Expected behavior**
that the barebones basic example of making an `en_US` dictionary would work out of the box.

**Additional context**
If applicable, post the output of :

```python
import enchant
d = enchant.Dict()
print(vars(d))
```

Output ```
>>> import enchant
>>> d = enchant.Dict()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/genche/.local/lib/python3.8/site-packages/enchant/__init__.py", line 541, in __init__
    _EnchantObject.__init__(self)
  File "/home/genche/.local/lib/python3.8/site-packages/enchant/__init__.py", line 144, in __init__
    self._init_this()
  File "/home/genche/.local/lib/python3.8/site-packages/enchant/__init__.py", line 548, in _init_this
    this = self._broker._request_dict_data(self.tag)
  File "/home/genche/.local/lib/python3.8/site-packages/enchant/__init__.py", line 286, in _request_dict_data
    self._raise_error(e_str % (tag,), DictNotFoundError)
  File "/home/genche/.local/lib/python3.8/site-packages/enchant/__init__.py", line 233, in _raise_error
    raise eclass(default)
enchant.errors.DictNotFoundError: Dictionary for language 'en_US' could not be found
>>> print(vars(d))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'd' is not defined
>>>

Thanks!

**Comment by dmerejkowsky** [comment]
>  that the barebones basic example of making an en_US dictionary would work out of the box.

I don't think that's a good idea. Remember that PyEnchant is only a wrapper on top of Enchant, which itself is just a wrapper over other providers, who all need dictionaries. to be installed separately

We do package an English dictionary and the hunspell provider on Windows because installing dictionaries and providers on this platform is difficult. 

On Linux an macOS on the other hand, we let people install providers and dictionaries from their package managers. More info [in the documentation](https://pyenchant.github.io/pyenchant/install.html#on-linux) 

Hope this helps, don't hesitate to re-open if you have more questions.

**Comment by bgenchel** [comment]
hi, I was able to get it working on mac after brew installing enchant. Thanks for getting back to me!

It was a little unclear to me that I would need to install other packages to get the wrapper working though, perhaps that could be made more explicit?

**Comment by dmerejkowsky** [comment]
Hum, we could add a link to the documentation in the error message :)
