### ISSUE TITLE
Question about dictionary locations

### ISSUE THREAD

**Issue by hellsworth** [pyenchant/pyenchant#200]
Hello.. This is not a bug but rather a query meant for the devs of pyenchant.

I'm the maintainer of the [cherrytree](https://github.com/giuspen/cherrytree) snap and am looking for a way to direct the ubuntu python-enchant package (which I *believe* is the same thing as pyenchant?) to find the dictionaries in a non-standard location: $SNAP/usr/share/hunspell. A quick look at the pyenchant source didn't reveal any env vars I could set for this or other method. So is there any way I can make sure python-enchant finds the installed dictionaries within $SNAP?

Many thanks in advance!

**Comment by dmerejkowsky** [comment]
>  to direct the ubuntu python-enchant package (which I believe is the same thing as pyenchant?) 

Not sure. It seems python-enchant has been [packaged for debian](https://tracker.debian.org/news/1107295/pyenchant-301-1-migrated-to-testing/). 

But a [search for python-enchant in Ubuntu packages](https://packages.ubuntu.com/search?keywords=python-enchant&searchon=names) shows an old version for eoan, and no version at all for focal, don't know why.

> Is there any way I can make sure python-enchant finds the installed dictionaries within $SNAP?

It depends on the provider. The question has already been asked and has been [answered by one the Enchant maintainers](https://github.com/pyenchant/pyenchant/issues/167#issuecomment-593150599).

I guess we should add this to the FAQ

**Comment by dmerejkowsky** [comment]
Done in 612d482d01b38d2c7a4c001d478befe7741f70be

**Comment by dmerejkowsky** [comment]
Closing - see also #201 which may help for debugging.

**Comment by hellsworth** [comment]
Thanks so much @dmerejkowsky !!

**Comment by dmerejkowsky** [comment]
> But a search for python-enchant in Ubuntu packages shows an old version for eoan, and no version at all for focal, don't know why.

I figured it out:  was not looking for the correct package name - on Ubuntu, it's called python3-enchant.

The sad news is that python3-enchant in focal is still at version 2.0.

We'll have to wait for groovy to be able to install python3-enchant on ubuntu. Oh well, that's why we have pip ;)

**Comment by hellsworth** [comment]
Ah ok well actually the snap build still uses an 18.04 base, which does have regular python-enthant (again, still at 2.0.0-1).

I did try setting the runtime variable:
```ENCHANT_CONFIG_DIR=$SNAP/usr/share/hunspell```

But still, enchant is not finding the hunspell dictionaries in this folder. @dmerejkowsky Any thoughts on how else I should point to these dictionaries?

**Comment by dmerejkowsky** [comment]
So, heres's what I found:

* On Ubuntu 18.04, the enchant package is called libenchant1c2a and is _not_ compiled with hunspell support:

```bash
dpkg -L libenchant1c2a | grep enchant/lib
/usr/lib/x86_64-linux-gnu/enchant/libenchant_aspell.so
/usr/lib/x86_64-linux-gnu/enchant/libenchant_hspell.so
/usr/lib/x86_64-linux-gnu/enchant/libenchant_ispell.so
/usr/lib/x86_64-linux-gnu/enchant/libenchant_myspell.so
```

* On Ubuntu 20.04, this works as expected

```bash
$ apt install python3-enchant
$ mkdir -p /snap/hunspell
$ cp  /usr/share/hunspell/* /snap/hunspell
$ apt remove hunspell-en-us
$  ENCHANT_CONFIG_DIR=/snap/ python3
>>> import enchant
>>> enchant.list_dicts()
```
```
