### ISSUE TITLE
Set Edit Distance

### ISSUE THREAD

**Issue by tahirahmad2030** [pyenchant/pyenchant#213]
Thank you for taking the time to open a bug report!

If you haven't already, take a time to look at the [documentation](https://pyenchant.github.io/pyenchant/). Maybe the answer to your problem can be found there?

If not, please fill in the details below to help us help you 🙂

**Environment**
Python version: 3.6
Operation system: Ubuntu 16.04

**Additional context**
This library doesn't seem to have an option of edit distance. If it does how to set it.
I want a term to change only to certain extent and stop it if it is changed too much from the acutal word.
 

**Steps to Reproduce**
Please specify steps to reproduce the incorrect behavior:
I have loaded custom terms to enchant which has blind as one term. 

When I input a term `BCvNL` it is corrected to `blind`. It is not even close. 

**Expected behavior**
Please tell us what you expected to happen:
The expected behavior should be that it should not be corrected at all, the input term `BCvNL` should be corrected to `BCvNL` or  empty list but not to `Blind`.

**Additional context**
If applicable, post the output of :

```python
import enchant
d = enchant.Dict()
print(vars(d))
```

Thanks!

**Comment by dmerejkowsky** [comment]
Hello,

It seems you did not edit the bug report template. Thus it's a bit hard for me to understand your request. Can you please edit the issue description with the requested information ?

**Comment by tahirahmad2030** [comment]
@dmerejkowsky I have edited the issue

**Comment by dmerejkowsky** [comment]
Looks like the feature you want is not exposed by the C enchant library (see https://github.com/AbiWord/enchant/blob/master/src/enchant.h for the reference) - so there's not much we can do here.

Closing.
