### ISSUE TITLE
AppleSpell headaches.

### ISSUE THREAD

**Issue by jenstroeger** [pyenchant/pyenchant#216]
More of a question at this point, and specific to macOS. I do have [aspell](http://aspell.net/) installed from MacPorts:
```
> which aspell
/opt/local/bin/aspell
> aspell --version
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.8)
```
and I’d like to use it for enchant. So:
```
>>> import enchant
>>> enchant.__version__
'3.1.1'
>>> b = enchant.Broker()
>>> b.set_ordering("*", "aspell,ispell")
```
at which point I would hope that aspell will be prioritized above all others. But that seems not the case:
```
>>> en = b.request_dict("en_US")
>>> en.provider
<Enchant: AppleSpell Provider>
```
This is probably not a pyenchant issue though, considering it thunks the call down to the native [`enchant_broker_set_ordering()` library call](https://github.com/AbiWord/enchant/blob/ab1b29f0c326c517d0b88c084a3e0bd38f6d32a0/src/enchant.h#L101-L115). I didn’t see any issues concerning this in the native enchant library, but perhaps @rrthomas has some more background on enchant on macOS with providers other than AppleSpell?

AppleSpell is tremendously puzzling because:
```
>>> en.check('עבודה')  # Hebrew, not English.
True
>>> en.check('Deutsch')  # German, not English.
True
>>> de = b.request_dict('de_DE')
>>> de.provider
<Enchant: AppleSpell Provider>
>>> de.check('she')  # English, not German.
True
>>> de.check('their')  # English, not German.
True
```
This goes on forever. Is it possible that AppleSpell functions as a proxy for language-specific dictionaries and just mushes them all together into one?

**Comment by rrthomas** [comment]
What version of Enchant is this? (The version number you report isn't an Enchant version number, so I presume it's for PyEnchant.)

**Comment by jenstroeger** [comment]
@rrthomas, hm, thank you for sending me onto a dig-around 😉

Apparently, there are two port files for enchant, [enchant](https://github.com/macports/macports-ports/tree/master/textproc/enchant) (enchant version 1.6.0) and [enchant2](https://github.com/macports/macports-ports/tree/master/textproc/enchant2) (enchant version 2.2.11). I had installed the old one, of course.

Second, I noticed that the MacPorts build didn’t enable aspell:
```
> port installed enchant2
None of the specified ports are installed.
> port installed enchant
The following ports are currently installed:
  enchant @1.6.0_5+applespell (active)
```
so I rebuild that:
```
> sudo port install enchant +aspell+applespell
--->  Computing dependencies for enchant
...
```
When that finished, lo and behold aspell became available as a provider:
```
>>> import enchant
>>> b = enchant.Broker()
>>> b.set_
b.set_ordering( b.set_param(   
>>> b.set_ordering("aspell")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: set_ordering() missing 1 required positional argument: 'ordering'
>>> b.set_ordering("*", "aspell")
>>> en = b.request_dict("en_US")
>>> en.provider
<Enchant: Aspell Provider>
>>> en.check('עבודה')
False
```
I’m adding enchant2 now.

Still, why AppleSpell returns such colorful results is anyone’s guess.

**Comment by dmerejkowsky** [comment]
Thank you both for taking the time to open a bug report, investigate the issue and find a solution :)

I never tried PyEnchant on macOS with anything other that `brew`, glad to learn it can work with `macports` as well.

Will update documentation soon.

Cheers!

**Comment by jenstroeger** [comment]
@dmerejkowsky, no problem! Feel free to close the issue now.

**Comment by jenstroeger** [comment]
@dmerejkowsky, no problem! Looking at the interface to the native enchant library, I noticed

https://github.com/pyenchant/pyenchant/blob/abdd73f25588e72c82dc940d1c4798be957e7b43/enchant/_enchant.py#L98-L108

which aligns with having both libraries installed on the Mac (MacPorts):
```
-rwxr-xr-x 1 root admin 51K Oct  8 19:51 libenchant-2.2.dylib
-rw-r--r-- 1 root admin 49K Oct  8 19:51 libenchant-2.a
lrwxr-xr-x 1 root admin  20 Oct  8 19:51 libenchant-2.dylib -> libenchant-2.2.dylib
-rwxr-xr-x 1 root admin 47K Oct  8 19:33 libenchant.1.dylib
-rw-r--r-- 1 root admin 45K Oct  8 19:33 libenchant.a
lrwxr-xr-x 1 root admin  18 Oct  8 19:33 libenchant.dylib -> libenchant.1.dylib
```
Would it make sense at all to allow the user to prefer v1 or v2 or would you like to keep it transparent?

**Comment by dmerejkowsky** [comment]
> Would it make sense at all to allow the user to prefer v1 or v2 or would you like to keep it transparent?

I can't think of a good reason. If you have both enchan1 and enchant2 install, it makes sense to use the latest version no?

Also, you can already customize the way PyEnchant looks for the Enchant C library by setting the PYENCHANT_LIBRARY_PATH environment variable

**Comment by jenstroeger** [comment]
Makes sense, fair enough 👍
