### ISSUE TITLE
Update URL for Enchant

### ISSUE THREAD

**Issue by rrthomas** [pyenchant/pyenchant#220]
The URL for Enchant is out of date, and currently gives security errors.

I (the current Enchant maintainer!) suggest instead linking to: https://abiword.github.io/enchant/

**Comment by dmerejkowsky** [comment]
Hello, fellow maintainer :)

This has been fixed. We' ll need to make a new release so that the new URL also appears on pypi.org, but sadly this is blocked by #218 for now.

Thanks for letting me know.

**Comment by rrthomas** [comment]
Heh, I have my own PyPI woes in another project…
