### ISSUE TITLE
"Sep" considered incorrect in "en_US" dictionary

### ISSUE THREAD

**Issue by dgerstel** [pyenchant/pyenchant#233]
The month abbreviations (Jan .. Dec) work fine except September (Sep) as in the example below:
```python
import enchant
d = enchant.Dict("en_US")
d.check("Sep") # -> False
```
Is it an issue with `pyenchant` itself or an underlying dictionary?

**Environment**
Python version: 3.8.5
Operation system: Linux Fedora 33
enchant version: 3.2.0

Thanks!

**Comment by dmerejkowsky** [comment]
I'm pretty sure it's a problem in the underlying repository. What does `print(d.provider)` say ?

**Comment by dgerstel** [comment]
Oh, I got back to my jupyter notebook (I restarted everything) and the problem disappeared ("Sep" is correct).
Now the provider is `<Enchant: Hunspell Provider>`, but I don't know which provider was used then.
Sorry for the unnecessary issue (which I'm closing, since I can't reproduce the problem).

Thanks :)
