### ISSUE TITLE
There are some potential problem to install PyEnchant 3.2

### ISSUE THREAD

**Issue by imrankhan441** [pyenchant/pyenchant#252]
I can not find any relevant source to install PyEnchant 3.2 specifically. The official website shows how to install with pip, but installing with pip not proper working. Can you please provide specific reference to install PyEnchant 3.2 with apt?

**Comment by dmerejkowsky** [comment]
Hello,

Sorry but I'm not sure I understand your problem correctly.

> installing with pip not proper working. 

Do you mean that you tried to install PyEnchant with pip and it failed? If so, could you please post an error message here?

>  Can you please provide specific reference to install PyEnchant 3.2 with apt?

I'm assuming your are using a Linux distribution based on Debian. The good news is that PyEnchant 3.2 has been packaged or Debian Sid: https://packages.debian.org/search?keywords=python-enchant

In that case, you should either switch to Debian Sid or wait for the package to be published to whatever distribution you are using.

Hope this helps :)

**Comment by dmerejkowsky** [comment]
Let's assume it did help and close this. Feel free to re-open if necessary.
