### ISSUE TITLE
"ImportError: The 'enchant' C library was not found and maybe needs to be installed." on Google Colab

### ISSUE THREAD

**Issue by AtrikGit6174** [pyenchant/pyenchant#253]
In August 2020, I was working using the Enchant module. It was working perfectly, after having executed
`!apt install -qq enchant`
`!pip install pyenchant`
`import enchant`

I came back to it today (07 Aug 2021) and while I run it again, it raises the above ImportError.
I have also tried the below one, but it does not seem to help even if some installation is actually occurring...
`!apt install enchant`
`!pip install pyenchant`
`import enchant`

INSTALLATION  & ERROR DETAILS:

```
The following additional packages will be installed:
  aspell aspell-en dictionaries-common emacsen-common hunspell-en-us
  libaspell15 libenchant1c2a libhunspell-1.6-0 libtext-iconv-perl
Suggested packages:
  aspell-doc spellutils wordlist hunspell openoffice.org-hunspell
  | openoffice.org-core libenchant-voikko
The following NEW packages will be installed:
  aspell aspell-en dictionaries-common emacsen-common enchant hunspell-en-us
  libaspell15 libenchant1c2a libhunspell-1.6-0 libtext-iconv-perl
0 upgraded, 10 newly installed, 0 to remove and 40 not upgraded.
Need to get 396 kB/1,310 kB of archives.
After this operation, 5,353 kB of additional disk space will be used.
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/a/aspell/libaspell15_0.60.7~20110707-4ubuntu0.1_amd64.deb 404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/a/aspell/aspell_0.60.7~20110707-4ubuntu0.1_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Requirement already satisfied: pyenchant in /usr/local/lib/python3.7/dist-packages (3.2.1)
```

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-23-9cbbd4342b6b> in <module>()
      1 get_ipython().system('apt install -qq enchant')
      2 get_ipython().system('pip install pyenchant')
----> 3 import enchant

1 frames
/usr/local/lib/python3.7/dist-packages/enchant/_enchant.py in <module>()
    155         """
    156     )
--> 157     raise ImportError(msg)
    158 
    159 

ImportError: The 'enchant' C library was not found and maybe needs to be installed.
See  https://pyenchant.github.io/pyenchant/install.html
for details
```

![image](https://user-images.githubusercontent.com/64845750/128596224-d1c748cb-a2ab-484d-85fd-163cb6e0a145.png)

[I have implemented a method where the libraries are permanently installed on my GDrive, so you see a commented out installation commands. I have checked the GDrive and found them installed.]

ENVIRONMENT DETAILS:
`!lsb_release -a`
`!python --version`
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
Python 3.7.11

I have checked your https://pyenchant.github.io/pyenchant/install.html#on-linux but it didn't help much...
Kindly help. Thanks in advanced.

**Comment by dmerejkowsky** [comment]
Well, there's a clue here:

```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/a/aspell/libaspell15_0.60.7~20110707-4ubuntu0.1_amd64.deb 404  Not Found [IP: 91.189.88.152 80]
```

I guess you forgot to run `apt-get update`? Or maybe you could try and run `apt-get --fix-missing` as suggested?

**Comment by AtrikGit6174** [comment]
!apt-get update
![image](https://user-images.githubusercontent.com/64845750/128762283-3a0cf18f-f451-4af1-b658-78316010b6c7.png)

!apt-get --fix-missing
![image](https://user-images.githubusercontent.com/64845750/128762356-e816a092-2a22-4e18-9f60-d07db4b1c4a6.png)

I somehow feel like I have to specify something in the second command... Could you please clarify on that one? I am a beginner to all this stuff 😅 Further, I have permanently installed the modules in my Google Drive folder
![image](https://user-images.githubusercontent.com/64845750/128762653-8c7f6543-7854-40fd-a7e5-d9bd1774d347.png)

Still the same ImportError persists...

**Comment by dmerejkowsky** [comment]
Sorry, it's `!apt-get update --fix-missing`

**Comment by AtrikGit6174** [comment]
![image](https://user-images.githubusercontent.com/64845750/128976846-57546c6c-9f57-4122-a4e9-72813522d588.png)

But the C library ImportError exists for "enchant"... I don't really understand...

**Comment by dmerejkowsky** [comment]
They are two different "enchant" libraries.

The first one is written in Python and is called PyEnchant. You intsall it with pip by running `pip install enchant`

The second one is written in C/C++ and is called "Enchant" or "C Enchant". You install it with `apt`

Now, PyEnchant *needs* C Enchant to run. That's why when you run `import enchant` from Python, it tries to find the C Enchant library on the system, and when it fails, it runs "ImportError".

So, based on your messages I think the C Enchant library is *not* installed and this is why 'import enchant' fails.

To be sure, we can run:

```
apt-list --installed | grep enchant
```

And if the above command only shows a warning message:

```
apt update
apt install enchant --fix-missing
```

**Comment by AtrikGit6174** [comment]
OK Sir, this one worked. But I am unsure of the fact whether it will be permanently installed on the GDrive or it will be on the temporary basis during the runtime of the instance. I will get back to you on that matter.
I prefer a permanent install as it save effort and internet data on my part.
Thanks a lot @dmerejkowsky Sir.

**Comment by dmerejkowsky** [comment]
Glad I could help. Have a nice day.

**Comment by AtrikGit6174** [comment]
I think we cannot specify a location using the "apt install" method unlike pip install. I checked this and found that I will have to run the "apt install enchant --fix-missing" everytime I run the Colab notebook, even though using the "pip install" I have installed pyenchant and enchant in my GDrive folder...

![image](https://user-images.githubusercontent.com/64845750/129143582-c4efbb21-dafb-45b9-b624-0f1e113809fa.png)

Is there no workaround for this?

**Comment by dmerejkowsky** [comment]
I don't know if there's a workaround, sorry. But I think it's more an issue about Google Colab, not PyEnchant. Maybe ask them ?
