### ISSUE TITLE
Unable to install C library on Mac M1 

### ISSUE THREAD

**Issue by sagnik-sahoo** [pyenchant/pyenchant#260]
(python_env) sagniksahoo@Sagniks-MacBook-Air Python % brew install enchant
fatal: Could not resolve HEAD to a revision
Warning: No available formula or cask with the name "enchant".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
(python_env) sagniksahoo@Sagniks-MacBook-Air Python % 

I am getting the above error while installing.

**Comment by dmerejkowsky** [comment]
Looks like a problem with homebrew, not PyEnchant. You should try and follow instruction from [HomeBrew's troubleshooting page](https://docs.brew.sh/Troubleshooting)
