### ISSUE TITLE
No correct spelling suggestions 

### ISSUE THREAD

**Issue by aasalem10** [pyenchant/pyenchant#270]
Not sure if this is a Bug or otherwise. The misspelled word ' selackted' does not return a correct suggestion. 
------------------------------------------------------------/
Suggestion for tst : ['tat', 'ts', 'st', 'test', 'est', 'tit', 'tot', 'tut', 'tsp', 't st', 'ts t']
Suggestion for pychecker : ['checker']
Suggestion for shuld : ['should']
Suggestion for wrd : ['wed', 'rd', 'ward', 'word', 'wad', 'wry', 'w rd']
Suggestion for corection : ['correction', 'connection', 'confection', 'convection', 'erection']
Suggestion for usear : ['user', 'sear', 'u sear', 'us ear', 'us-ear', 'arouse']
Suggestion for selackted : ['tessellated']
Suggestion for usr : ['use', 'us', 'user', 'usu', 'us r', 'USSR']
Suggestion for finaanchial : ['financial']
Suggestion for usinf : ['using', 'us inf', 'us-inf', 'sinus']
Suggestion for finachial : ['financial']
Suggestion for cuse : ['cutie', 'cues', 'cue', 'use', 'cause', 'curse', 'cruse', 'ecus', 'cuss', 'case', 'cure', 'ruse', 'cute', 'muse', 'cusp']
Suggestion for absoulte : ['absolute', 'soulmate']
---------------------------------------/
text in file: 'mytextfile.txt'
'this is tst file for pychecker 
if it all goes well it shuld read 
file line wrd by word
this corection is usear 
selackted
usr can skip words is he is using medical or finaanchial data
usinf finachial data may cuse malfunction in the absoulte value'
----------------------------------------------------/
**Environment**
Python version: sys.path
['/home/alaa/pycharm/pycharm-community-2021.2.3/plugins/python-ce/helpers/pydev', '/home/alaa/PycharmProjects/pythonProject/stocks', '/home/alaa/pycharm/pycharm-community-2021.2.3/plugins/python-ce/helpers/third_party/thriftpy', '/home/alaa/pycharm/pycharm-community-2021.2.3/plugins/python-ce/helpers/pydev', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/alaa/PycharmProjects/pythonProject/stocks/venv/lib/python3.8/site-packages', '/home/alaa/PycharmProjects/pythonProject/stocks']

python 3.8
virtualenv 20.0.17 from /usr/lib/python3/dist-packages/virtualenv/__init__.py
pyenchant==3.2.2
pyspellchecker==0.6.2
Operation system:
Linux alaa-XPS13-9333 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
python 3.8
PyCharm 2021.2.3 (Community Edition)
Build #PC-212.5457.59, built on October 19, 2021
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-55-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 984M
Cores: 4
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: org.sonarlint.idea (6.3.0.39716), izhangzhihao.rainbow.brackets (6.21), com.kite.intellij (1.9.4)
Current Desktop: MATE
**Additional context**

**Steps to Reproduce**
Please specify steps to reproduce the incorrect behavior:

`dict = enchant.Dict("en_US")
#dict = SpellChecker("en_us")

spell_filename = 'mytextfile.txt'
with open(spell_filename, "r", encoding="utf-8") as f:
     for line in f:
        line = line.rstrip('\r\n')
        line = line.split()
        #missword.clear()
        #options.clear()
        for word in line:
            if dict.check(word) == False:
               missword.append(word)
               print (word)
            else:
                pass
     #print("The misspelled words are : " + str(missword))
for word in missword:
    print("Suggestion for " + word + " : " + str(dict.suggest(word)))
    options.append((dict.suggest(word)))
`
**Expected` behavior**
Please tell us what you expected to happen:
Suggestion for selackted : ['tessellated']   == selackted : ['selected']

**Additional context**
If applicable, post the output of :

```python
import enchant
d = enchant.Dict()
print(vars(d))
```
{'provider': <Enchant: Hunspell Provider>, 'tag': 'en_US', '_broker': <enchant.Broker object at 0x7ff1cec98ca0>, '_this': 41896944, '_Dict__describe_result': ('en_US', 'hunspell', 'Hunspell Provider', '/usr/lib/x86_64-linux-gnu/enchant-2/enchant_hunspell.so')}

Thanks!

**Comment by dmerejkowsky** [comment]
> The misspelled word ' selackted' does not return a correct suggestion.

I guess 'selackted' is too far from 'selected' for Hunspell to see the correction. Probably not something we can fix in PyEnchant - we're just a wrapper on top of Enchant, which itself is a wrapper on top of Hunspell.

**Comment by aasalem10** [comment]
You may delete this post if you see so.
Thanks,
