### ISSUE TITLE
Unable to use "enchant" on Azure Datarbicks

### ISSUE THREAD

**Issue by vikassinha167** [pyenchant/pyenchant#278]
Hi,

When I install "pyenchant" using PyPI on my Azure Databricks cluster it gets successfully installed. But when I run the command "import enchant" , it fails with the following error - "The 'enchant' C library was not found and maybe needs to be installed.". 
![ImportError](https://user-images.githubusercontent.com/20685680/148175228-856ec421-f698-4b99-a913-5fead10cb4ed.PNG)
![LibraryInstalledSucessfully](https://user-images.githubusercontent.com/20685680/148175243-40c9f6f9-5a8b-4591-81c3-27d686341268.PNG)

Kindly help.

Regards,
Vikas

**Comment by dmerejkowsky** [comment]
This is expected - pyenchant usually does not (and cannot) work out of the box when installed from pypi.

You will have to figure out how to install the *C* enchant library, and at least one spelling backend supported by enchant, and one dictionary) before being able to use the PyEnchant package.

More info [in the documentation](https://pyenchant.github.io/pyenchant/install.html)
