### ISSUE TITLE
Fix Apple Silicon documentation

### ISSUE THREAD

**Issue by dmerejkowsky** [pyenchant/pyenchant#281]
The documentation was updated while we were investigation #265, but not completely, as shown by #280

In particular, we need to take into account this comment:

* https://github.com/pyenchant/pyenchant/issues/265#issuecomment-998965819 (by @Simonmaignan)

**Comment by Simonmaignan** [comment]
I'm working on this issue on [a branch from my fork](https://github.com/Simonmaignan/pyenchant/tree/fix-apple-silicon-doc).

**Comment by dmerejkowsky** [comment]
Nice, thanks :)
