### ISSUE TITLE
enchant.errors.DictNotFoundError: Dictionary for language 'Russian' could not be found

### ISSUE THREAD

**Issue by gorgulenkozxc** [pyenchant/pyenchant#289]
**Environment**
Python version: 3.8.12
Operation system: Linux CentOS 7

**Steps to Reproduce**
1. pip3.8 install pyenchant
2. [Russian.zip](https://github.com/pyenchant/pyenchant/files/8584858/Russian.zip)
3. Put Russian.dic and Russian.aff into _/usr/share/myspell/_
4. 
```python
import enchant
print(enchant.list_languages())  # [..., 'en_ZW', 'Russian']
print(enchant.list_dicts()) # [..., ('Russian', <Enchant: Myspell Provider>)]
print(enchant.dict_exists("Russian")) # False
d = enchant.Dict("Russian") # enchant.errors.DictNotFoundError: Dictionary for language 'Russian' could not be found
```

**Expected behavior**
`print(enchant.dict_exists("Russian")) # True`
If it's in same folder as others dictionaries
If it's shown in languages
If it's shown in dictionaries
It must exist

**Additional context**
`{'provider': <Enchant: Myspell Provider>, 'tag': 'en_US', '_broker': <enchant.Broker object at 0x7f846fc4ba60>, '_this': 26439088, '_Dict__describe_result': ('en_US', 'myspell', 'Myspell Provider', '/usr/lib64/enchant/libenchant_myspell.so')}`

**Comment by dmerejkowsky** [comment]
Hello,

I did manage to make enchant work in Russian using the official docker image for CentOS7:

```
$ yum install python3
$ yum install enchant
$ yum install hunspell-ru
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install -U pip wheel
$ pip install pyenchant
$ python
>>> import enchant
>>> ru_dict = enchant.request_dict("ru_RU")
>>> ru_dict.check("Привет")
True
```

Is there a reason you can't use the `hunspell-ru` centos package ?

**Comment by gorgulenkozxc** [comment]
Thank you for solution, it works great
