### ISSUE TITLE
"check whether a word is spelled correctly" is spelled incorrectly

### ISSUE THREAD

**Issue by jdalbey** [pyenchant/pyenchant#294]
There is a spelling error in the help text (which some might find amusingly ironic). 

**Environment**
Python version: Python 3.6.9 
Operation system: Linux Mint

**Steps to Reproduce**

```python
import enchant
help(enchant)
```
then in the output that is produced observe:
```
     |  The important methods of this class include:
     |  
     |      * check():              check whether a word id spelled correctly
```
The word 'id' should be 'is'.

**Comment by dmerejkowsky** [comment]
Well, isn't that ironic :)

This was fixed in 282252bd2c73c667b047360ab6232bf88a7dfab5 by @spagh-eddie - we "just" need to make a new release
