### ISSUE TITLE
Need to install the libenchant *-dev* package for PyEnchant to work on Ubuntu 22 and Ubuntu 18

### ISSUE THREAD

**Issue by vedmed85** [pyenchant/pyenchant#298]
>>> import enchant
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/enchant/__init__.py", line 81, in <module>
    from enchant import _enchant as _e
  File "/usr/local/lib/python3.6/dist-packages/enchant/_enchant.py", line 157, in <module>
    raise ImportError(msg)
ImportError: The 'enchant' C library was not found and maybe needs to be installed.
See  https://pyenchant.github.io/pyenchant/install.html
for details

**Comment by dmerejkowsky** [comment]
> No clear installation manual

I don't get it. Did you not see the URL you just copy/pasted? It contains instructions to install PyEnchant...

**Comment by vedmed85** [comment]
i found.
libenchant stored in the package libenchant-dev
so before pip needed
sudo apt-get install libenchant-dev

**Comment by pmhahn** [comment]
> Hum. PyEnchant should be able to find the C library _without_ the `-dev` package

Many Linux distributions (Debian, Ubuntu, SUSE, RedHat, …) separate *runtime* files from *development* files: the later are required for actually running programs while the later are only required if you want to compile your own programs: They include header files and other control files like Makefiles or AutoConf fragments.
As PyEnchant is a wrapper around the low-level C-library `libenchant` it needs those headers and as such you must install the `libenchant-dev` package which contains them. How those packages are named heavily depends the one Linux distribution you use.
After the build stage the development package is no longer needed as the generated PyEnchant wrapper only needs the _runtime_ package. You can then remove the _development_ package until you want to build (a new version of) PyEnchant again.

Separating runtime files from development files not only shrinks the space required on your file system, but also slightly can improve security as you should not install unneeded software on your servers as each peace of software might contain bugs and simplifies the life of hackers as they have more things available to be abused.
