### ISSUE TITLE
nixos useage

### ISSUE THREAD

**Issue by amirreza8002** [pyenchant/pyenchant#315]
hello
so i know it's probably a nix thing
but just in case, if you know a workaround

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/amirreza/projects/enc/.venv/lib/python3.11/site-packages/enchant/__init__.py", line 81, in <module>
    from enchant import _enchant as _e
  File "/home/amirreza/projects/enc/.venv/lib/python3.11/site-packages/enchant/_enchant.py", line 161, in <module>
    e = ctypes.cdll.LoadLibrary(enchant_lib_path)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/current-system/sw/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/run/current-system/sw/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libenchant-2.so.2: cannot open shared object file: No such file or directory
```

i'm getting this error when trying to import enchant

also my shell.nix :
```
let
  nixpkgs = fetchTarball "https://github.com/NixOS/nixpkgs/tarball/nixos-23.11";
  pkgs = import nixpkgs { config = {}; overlay = []; };
in

pkgs.mkShell {
  packages = with pkgs; [
    gnumake
    libgcc
    gcc13
    rustup
    enchant
    binutils
  ];
}
```

please let me know if it is a nixos problem so i can go bug the community :p

**Comment by pmhahn** [comment]
Read the FAQ on https://pypi.org/project/pycrypto/:
> Warning: in general, PyEnchant will not work out of the box after having been installed with pip (or any other installation method) - see the [documentation](https://pyenchant.github.io/pyenchant/) for more details.

PypEnchant is just a *wrapper* for `enchant`, which you must install first on your operating system *including* dictionaries.

**Comment by dmerejkowsky** [comment]
Hum - I think we need to re-open - unless I'm mistaken, enchant *is* listed in the nixos packages, so in theory this should work.

**Comment by pmhahn** [comment]
> Hum - I think we need to re-open - unless I'm mistaken, enchant _is_ listed in the nixos packages, so in theory this should work - but the bug maybe in ctypes - we had the same kind of problem with alpine if I recall correctly.

We (pyenchant) are not responsible for how [NixOS](https://nixos.org/) does **their** packaging of pyenchant; complain there!
1. You must have your basic build tools like a C(++) compiler installed
2. You must install [enchant](https://abiword.github.io/enchant/) first
3. You must have the **development files** (header files, symbolic links for shared libraries, …) available for enchant, Python, … to then be able to install PyEnchant

Other Linux distributions like Debian, Ubuntu, SuSE, CentOS, Arch, … have pre-build packages as they invested their time to do that for you once; if you prefer to use other distributions or prefer to compile everything yourself, then also please solve these problems yourself. There are too many distributions for us to support them all.

Hint: Search your file system for the file `libenchant-2.so.2` and ask yourself, why the dynamic linker does not find it: Usually it looks in locations like `/usr/lib/` or `/usr/lib/x86_64-linux-gnu/` or `/lib/` or `/usr/local/lib/` or whatever you configured via `$LD_LIBRARY_PATH`; if Enchant is (not) installed or into some other location, `dlopen()` will not find it and as such PyEnchange will not work.
